services:
  dislinkt-server-db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5436:5432"
    container_name: dislinkt-server-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345

  accounts-api:
    image: dislinkt/accounts-api:latest
    container_name: accounts-api
    depends_on:
      - dislinkt-server-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dislinkt-server-db:5432/accounts-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    ports:
      - "8080:8080"

  offers-api:
    image: dislinkt/offers-api:latest
    container_name: offers-api
    depends_on:
      - dislinkt-server-db
    ports:
      - "8083:8083"

  chat-api:
    image: dislinkt/chat-api:latest
    container_name: chat-api
    depends_on:
      - dislinkt-server-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dislinkt-server-db:5432/chat-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    ports:
      - "8084:8084"
